language: python
env:
    - TOX_ENV=py33
    - TOX_ENV=py34
    - TOX_ENV=py35
    - TOX_ENV=pypy

install:
    - pip install tox --use-mirrors

script:
    - tox -e $TOX_ENV

after_success:
    - if [[ $TRAVIS_PYTHON_VERSION != 'pypy' ]]; then pip install coveralls --use-mirrors ; coveralls ; fi

notifications:
  email: false